from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from reporting import normalize_report, report_to_markdown


MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
VALID_SEVERITIES = {"Low", "Medium", "High", "Critical"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze a network-flow summary with SOCPilot and generate "
            "structured JSON, Markdown, and performance reports."
        )
    )
    parser.add_argument(
        "summary_path",
        type=Path,
        help="Path to the network-flow summary JSON file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/incident_report.json"),
        help="Path used to save the generated JSON incident report.",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=700,
        help="Maximum number of tokens generated by the model.",
    )
    parser.add_argument(
        "--show-raw-output",
        action="store_true",
        help="Print the unprocessed model response.",
    )
    return parser.parse_args()


def validate_report(report: Any) -> list[str]:
    errors: list[str] = []

    if not isinstance(report, dict):
        return ["The response must be a JSON object."]

    required_fields = {
        "severity",
        "confidence",
        "attack_type",
        "summary",
        "mitre_attack",
        "evidence",
        "recommendations",
    }

    missing = required_fields - report.keys()
    if missing:
        errors.append(f"Missing fields: {sorted(missing)}")

    severity = report.get("severity")
    if severity not in VALID_SEVERITIES:
        errors.append(
            "severity must be Low, Medium, High, or Critical."
        )

    confidence = report.get("confidence")
    if not isinstance(confidence, int) or not 0 <= confidence <= 100:
        errors.append(
            "confidence must be an integer between 0 and 100."
        )

    for field in ("attack_type", "summary"):
        value = report.get(field)
        if not isinstance(value, str) or not value.strip():
            errors.append(f"{field} must be a non-empty string.")

    for field in ("mitre_attack", "evidence", "recommendations"):
        if not isinstance(report.get(field), list):
            errors.append(f"{field} must be an array.")

    mitre_entries = report.get("mitre_attack", [])
    if isinstance(mitre_entries, list):
        for index, entry in enumerate(mitre_entries):
            if not isinstance(entry, dict):
                errors.append(
                    f"mitre_attack[{index}] must be an object."
                )
                continue

            if not isinstance(entry.get("technique_id"), str):
                errors.append(
                    f"mitre_attack[{index}].technique_id must be a string."
                )

            if not isinstance(entry.get("technique_name"), str):
                errors.append(
                    f"mitre_attack[{index}].technique_name must be a string."
                )

    evidence_entries = report.get("evidence", [])
    if isinstance(evidence_entries, list):
        for index, entry in enumerate(evidence_entries):
            if not isinstance(entry, dict):
                errors.append(
                    f"evidence[{index}] must be an object."
                )
                continue

            for field in (
                "feature",
                "observed_value",
                "interpretation",
            ):
                if not isinstance(entry.get(field), str):
                    errors.append(
                        f"evidence[{index}].{field} must be a string."
                    )

    recommendations = report.get("recommendations", [])
    if isinstance(recommendations, list):
        for index, recommendation in enumerate(recommendations):
            if not isinstance(recommendation, str):
                errors.append(
                    f"recommendations[{index}] must be a string."
                )

    return errors


def extract_json(text: str) -> dict[str, Any]:
    text = text.strip()

    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")

        if start == -1 or end == -1 or end <= start:
            raise ValueError(
                "No JSON object was found in the model output."
            )

        result = json.loads(text[start : end + 1])

    if not isinstance(result, dict):
        raise ValueError(
            "The model response was not a JSON object."
        )

    return result


def normalize_confidence(
    report: dict[str, Any],
) -> dict[str, Any]:
    confidence = report.get("confidence")

    if isinstance(confidence, bool):
        return report

    if isinstance(confidence, str):
        cleaned = confidence.strip().rstrip("%")

        try:
            value = float(cleaned)
        except ValueError:
            return report

    elif isinstance(confidence, (int, float)):
        value = float(confidence)

    else:
        return report

    if 0 <= value <= 1:
        value *= 100

    value = max(0, min(100, value))
    report["confidence"] = round(value)

    return report


def save_json(
    path: Path,
    payload: dict[str, Any],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2),
        encoding="utf-8",
    )


def build_performance_report(
    *,
    elapsed: float,
    peak_memory_gib: float,
    input_tokens: int,
    output_tokens: int,
) -> dict[str, Any]:
    tokens_per_second = (
        output_tokens / elapsed
        if elapsed > 0
        else 0.0
    )

    return {
        "model": MODEL_ID,
        "hardware": {
            "gpu": torch.cuda.get_device_name(0),
            "runtime": "AMD ROCm",
            "pytorch_version": torch.__version__,
            "hip_version": torch.version.hip,
            "precision": "FP16",
        },
        "inference": {
            "generation_time_seconds": round(elapsed, 2),
            "peak_gpu_memory_gib": round(peak_memory_gib, 2),
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "output_tokens_per_second": round(
                tokens_per_second,
                2,
            ),
        },
        "artifacts": [
            "JSON incident report",
            "Markdown incident report",
            "Performance JSON",
        ],
        "local_inference": True,
    }


def print_banner() -> None:
    print()
    print("=" * 64)
    print("SOCPilot AI")
    print("Local Security Incident Analyzer")
    print("=" * 64)


def print_environment() -> None:
    print(f"Model          : {MODEL_ID}")
    print(f"GPU            : {torch.cuda.get_device_name(0)}")
    print(f"PyTorch        : {torch.__version__}")
    print(f"HIP / ROCm     : {torch.version.hip}")
    print("Precision      : FP16")
    print("Local inference: Yes")
    print("-" * 64)


def print_summary(
    *,
    report: dict[str, Any],
    elapsed: float,
    peak_memory_gib: float,
    input_tokens: int,
    output_tokens: int,
    json_path: Path,
    markdown_path: Path,
    performance_path: Path,
) -> None:
    mitre_entries = report.get("mitre_attack", [])
    mitre_text = "Not mapped"

    if mitre_entries:
        first_mapping = mitre_entries[0]
        technique_id = first_mapping.get(
            "technique_id",
            "Unknown",
        )
        technique_name = first_mapping.get(
            "technique_name",
            "Unknown",
        )
        mitre_text = (
            f"{technique_id} — {technique_name}"
        )

    tokens_per_second = (
        output_tokens / elapsed
        if elapsed > 0
        else 0.0
    )

    print()
    print("=" * 64)
    print("Analysis Complete")
    print("=" * 64)
    print(
        f"Severity        : "
        f"{report.get('severity', 'Unknown')}"
    )
    print(
        f"Confidence      : "
        f"{report.get('confidence', 'Unknown')}%"
    )
    print(
        f"Attack Type     : "
        f"{report.get('attack_type', 'Unknown')}"
    )
    print(f"MITRE ATT&CK    : {mitre_text}")
    print("-" * 64)
    print(f"Generation Time : {elapsed:.2f} seconds")
    print(f"Peak GPU Memory : {peak_memory_gib:.2f} GiB")
    print(f"Input Tokens    : {input_tokens}")
    print(f"Output Tokens   : {output_tokens}")
    print(
        f"Output Speed    : "
        f"{tokens_per_second:.2f} tokens/second"
    )
    print("-" * 64)
    print("Generated files:")
    print(f"  JSON        : {json_path}")
    print(f"  Markdown    : {markdown_path}")
    print(f"  Performance : {performance_path}")
    print("=" * 64)


def main() -> None:
    args = parse_args()

    if args.max_new_tokens <= 0:
        raise ValueError(
            "--max-new-tokens must be greater than zero."
        )

    if not args.summary_path.is_file():
        raise FileNotFoundError(
            f"Summary file not found: {args.summary_path}"
        )

    try:
        flow_summary = json.loads(
            args.summary_path.read_text(
                encoding="utf-8"
            )
        )
    except json.JSONDecodeError as error:
        raise ValueError(
            f"Summary file is not valid JSON: "
            f"{args.summary_path}"
        ) from error

    if not isinstance(flow_summary, dict):
        raise ValueError(
            "The summary file must contain one JSON object."
        )

    if not torch.cuda.is_available():
        raise RuntimeError(
            "PyTorch did not detect the AMD GPU."
        )

    print_banner()
    print_environment()
    print("Loading tokenizer and model...")

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_ID
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        dtype=torch.float16,
        device_map="auto",
    )
    model.eval()

    print("Model loaded successfully.")
    print("Preparing network-flow analysis...")

    system_prompt = """
You are SOCPilot, a local cybersecurity analysis agent.

Analyze the supplied aggregated network-flow statistics and return exactly one
valid JSON object using this schema:

{
  "severity": "Low | Medium | High | Critical",
  "confidence": 0,
  "attack_type": "",
  "summary": "",
  "mitre_attack": [
    {
      "technique_id": "",
      "technique_name": ""
    }
  ],
  "evidence": [
    {
      "feature": "",
      "observed_value": "",
      "interpretation": ""
    }
  ],
  "recommendations": []
}

Rules:
- Return JSON only.
- Do not use Markdown or code fences.
- Confidence must be an integer from 0 to 100.
- Infer behavior only from the supplied statistics.
- Do not invent IP addresses, domains, usernames, hashes, or other evidence.
- Evidence must reference values present in the supplied input.
- Use an empty MITRE ATT&CK array when a mapping is uncertain.
- Lower confidence when available evidence is weak.
- Keep recommendations concise and directly related to the observed activity.
""".strip()

    messages = [
        {
            "role": "system",
            "content": system_prompt,
        },
        {
            "role": "user",
            "content": (
                "Analyze this network-flow summary:\n"
                + json.dumps(
                    flow_summary,
                    indent=2,
                )
            ),
        },
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
    ).to(model.device)

    input_tokens = inputs["input_ids"].shape[1]

    torch.cuda.reset_peak_memory_stats()
    torch.cuda.synchronize()

    print("Running local ROCm inference...")

    start = time.perf_counter()

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=args.max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    torch.cuda.synchronize()
    elapsed = time.perf_counter() - start

    generated_ids = output_ids[
        0,
        input_tokens:,
    ]
    output_tokens = generated_ids.shape[0]

    raw_output = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    ).strip()

    if args.show_raw_output:
        print()
        print("--- Raw model output ---")
        print(raw_output)

    try:
        report = extract_json(raw_output)
        report = normalize_confidence(report)
        report = normalize_report(report)
    except (ValueError, json.JSONDecodeError) as error:
        print()
        print("JSON validation: FAILED")
        print(f"Reason: {error}")
        raise SystemExit(1)

    validation_errors = validate_report(report)

    if validation_errors:
        print()
        print("Schema validation: FAILED")

        for error in validation_errors:
            print(f"- {error}")

        raise SystemExit(1)

    print("JSON validation: PASSED")
    print("Schema validation: PASSED")

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    markdown_path = args.output.with_suffix(".md")
    performance_path = args.output.with_name(
        f"{args.output.stem}_performance.json"
    )

    save_json(
        args.output,
        report,
    )

    markdown_path.write_text(
        report_to_markdown(report),
        encoding="utf-8",
    )

    peak_memory_gib = (
        torch.cuda.max_memory_allocated()
        / 1024**3
    )

    performance = build_performance_report(
        elapsed=elapsed,
        peak_memory_gib=peak_memory_gib,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
    )

    save_json(
        performance_path,
        performance,
    )

    print_summary(
        report=report,
        elapsed=elapsed,
        peak_memory_gib=peak_memory_gib,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        json_path=args.output,
        markdown_path=markdown_path,
        performance_path=performance_path,
    )


if __name__ == "__main__":
    main()